{ 
    name: "",
    index: 0,
    argument: "Detections",
    argumentType: "null",
    tag: "annotation",
    tagType: "FLAT",
    context: "Detections",
    contextStep: "Detections",
    optional: false,
    multiple: false,
    choice: false,
    children: [ 
    { 
        name: "setDate",
        index: 0,
        argument: "String",
        argumentType: "null",
        tag: "date",
        tagType: "FLAT",
        context: "Detections",
        contextStep: "Detections",
        optional: false,
        multiple: false,
        choice: false,
        children: []
    }, 
    { 
        name: "setTime",
        index: 1,
        argument: "String",
        argumentType: "null",
        tag: "time",
        tagType: "FLAT",
        context: "Detections",
        contextStep: "Detections",
        optional: false,
        multiple: false,
        choice: false,
        children: []
    }, 
    { 
        name: "setFolder",
        index: 2,
        argument: "String",
        argumentType: "null",
        tag: "folder",
        tagType: "FLAT",
        context: "Detections",
        contextStep: "Detections",
        optional: false,
        multiple: false,
        choice: false,
        children: []
    }, 
    { 
        name: "setFilename",
        index: 3,
        argument: "String",
        argumentType: "null",
        tag: "filename",
        tagType: "FLAT",
        context: "Detections",
        contextStep: "Detections",
        optional: false,
        multiple: false,
        choice: false,
        children: []
    }, 
    { 
        name: "setPath",
        index: 4,
        argument: "String",
        argumentType: "null",
        tag: "path",
        tagType: "FLAT",
        context: "Detections",
        contextStep: "Detections",
        optional: false,
        multiple: false,
        choice: false,
        children: []
    }, 
    { 
        name: "setAttributes",
        index: 5,
        argument: "Properties",
        argumentType: "null",
        tag: "size",
        tagType: "STEP",
        context: "Detections",
        contextStep: "Properties",
        optional: false,
        multiple: false,
        choice: false,
        children: []
    }, 
    { 
        name: "setSize",
        index: 5,
        argument: "Size",
        argumentType: "null",
        tag: "size",
        tagType: "STEP",
        context: "Detections",
        contextStep: "Size",
        optional: false,
        multiple: false,
        choice: false,
        children: [ 
        { 
            name: "setWidth",
            index: 0,
            argument: "int",
            argumentType: "null",
            tag: "width",
            tagType: "FLAT",
            context: "Size",
            contextStep: "Size",
            optional: false,
            multiple: false,
            choice: false,
            children: []
        }, 
        { 
            name: "setHeight",
            index: 1,
            argument: "int",
            argumentType: "null",
            tag: "height",
            tagType: "FLAT",
            context: "Size",
            contextStep: "Size",
            optional: false,
            multiple: false,
            choice: false,
            children: []
        }, 
        { 
            name: "setDepth",
            index: 2,
            argument: "int",
            argumentType: "null",
            tag: "depth",
            tagType: "FLAT",
            context: "Size",
            contextStep: "Size",
            optional: false,
            multiple: false,
            choice: false,
            children: []
        } 
        ]
    }, 
    { 
        name: "setDetections",
        index: 6,
        argument: "List",
        argumentType: "Detection",
        tag: "object",
        tagType: "STEP",
        context: "Detections",
        contextStep: "List",
        optional: true,
        multiple: true,
        choice: false,
        children: [ 
        { 
            name: "setAttributes",
            index: 0,
            argument: "Properties",
            argumentType: "null",
            tag: "name",
            tagType: "STEP",
            context: "Detection",
            contextStep: "Properties",
            optional: false,
            multiple: false,
            choice: false,
            children: []
        }, 
        { 
            name: "setScore",
            index: 0,
            argument: "Double",
            argumentType: "null",
            tag: "name",
            tagType: "STEP",
            context: "Detection",
            contextStep: "Double",
            optional: false,
            multiple: false,
            choice: false,
            children: []
        }, 
        { 
            name: "setWeight",
            index: 0,
            argument: "Double",
            argumentType: "null",
            tag: "name",
            tagType: "STEP",
            context: "Detection",
            contextStep: "Double",
            optional: false,
            multiple: false,
            choice: false,
            children: []
        }, 
        { 
            name: "setName",
            index: 0,
            argument: "String",
            argumentType: "null",
            tag: "name",
            tagType: "STEP",
            context: "Detection",
            contextStep: "String",
            optional: false,
            multiple: false,
            choice: false,
            children: []
        }, 
        { 
            name: "setBox",
            index: 3,
            argument: "Box",
            argumentType: "null",
            tag: "bndbox",
            tagType: "STEP",
            context: "Detection",
            contextStep: "Box",
            optional: false,
            multiple: false,
            choice: false,
            children: [ 
            { 
                name: "setXmin",
                index: 0,
                argument: "int",
                argumentType: "null",
                tag: "xmin",
                tagType: "FLAT",
                context: "Box",
                contextStep: "Box",
                optional: false,
                multiple: false,
                choice: false,
                children: []
            }, 
            { 
                name: "setYmin",
                index: 1,
                argument: "int",
                argumentType: "null",
                tag: "ymin",
                tagType: "FLAT",
                context: "Box",
                contextStep: "Box",
                optional: false,
                multiple: false,
                choice: false,
                children: []
            }, 
            { 
                name: "setXmax",
                index: 2,
                argument: "int",
                argumentType: "null",
                tag: "xmax",
                tagType: "FLAT",
                context: "Box",
                contextStep: "Box",
                optional: false,
                multiple: false,
                choice: false,
                children: []
            }, 
            { 
                name: "setYmax",
                index: 3,
                argument: "int",
                argumentType: "null",
                tag: "ymax",
                tagType: "FLAT",
                context: "Box",
                contextStep: "Box",
                optional: false,
                multiple: false,
                choice: false,
                children: []
            } 
            ]
        } 
        ]
    } 
    ]
}